# Generated by Django 3.1.2 on 2020-10-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201029_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_content',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_text',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
